config/routes.rb
Rails.application.routes.draw do
  resources :technologies
  resources :projects
  get 'messages/list'

  resources :depenses
  devise_for :users
  get '/home' => 'pages#home'
  get '/portfolio' => 'pages#portfolio'
  get '/contact' => 'pages#contact'

  get '/project/:id' => 'pages#project'

  get '/pages/paye' => 'pages#paye'

  get '/messages' => 'messages#list'
  delete '/messages/:id' => 'messages#destroy'

  post '/pages/paye' => 'pages#addPaye'
  post 'contact' => 'pages#create'

  root 'pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :picture, styles: { large: "800x400>", medium: "300x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    technologies = ProjectTechnology.where(:project_id => @project.id)
    @technologies = []
    technologies.each do |technology|
      techno = Technology.find(technology.technology_id)
      @technologies.push(techno)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    @technologies = Technology.all
  end

  # GET /projects/1/edit
  def edit
    @technologies = Technology.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    puts "===============================".red
    puts "#{params[:technologies]}".red
    puts "===============================".red
    @technologies = params[:technologies]

    respond_to do |format|
      if @project.save
        @technologies.each do |t|
          linked = ProjectTechnology.new
          linked.project_id = @project.id
          linked.technology_id = t
          puts "===============================".yellow
          if linked.save
            puts "Link saved with project_id => #{@project.id}, technology_id => #{t}".green
          else
            puts "Link don't save with project_id => #{@project.id}, technology_id => #{t}".red
          end
          puts "===============================".yellow
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @technologies = params[:technologies]
    respond_to do |format|
      if @project.update(project_params)
        links = ProjectTechnology.where(:project_id => @project.id)
        technologies = []
        puts "========================".yellow
        links.each do |l|
          puts "#{l.technology_id}".green
          technologies.push(l.technology_id)
        end
        if @technologies != nil
          @technologies.each do |technology|
            request = ProjectTechnology.where("project_id = ? AND technology_id = ?", @project.id, technology).first
            puts "#{request}".light_blue
            if request == nil
              linked = ProjectTechnology.new
              linked.project_id = @project.id
              linked.technology_id = technology
              if linked.save
                puts "Save : #{linked}".green
              else
                puts "Can't save : #{linked}".red
              end
            else
              puts "Nil : #{request}".red
            end
          end
        end
        puts "========================".yellow
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    links = ProjectTechnology.where(:project_id => @project.id)
    puts "========================".yellow
    links.each do |l|
      puts "Destroy : #{l}".red
      l.destroy
    end
    puts "========================".yellow
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :github, :twitter, :url, :startdate, :enddate, :abstract, :picture)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="">
  <%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-6 col-xs-12">
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :github %><br>
        <%= f.text_field :github %>
      </div>
      <div class="field">
        <%= f.label :twitter %><br>
        <%= f.text_field :twitter %>
      </div>
      <div class="field">
        <%= f.label :url %><br>
        <%= f.text_field :url %>
      </div>
    </div>
    <div class="col-md-6 col-xs-12">
      <div class="field">
        <%= f.label :startdate %><br>
        <%= f.text_field :startdate %>
      </div>
      <div class="field">
        <%= f.label :enddate %><br>
        <%= f.text_field :enddate %>
      </div>
      <div class="field">
        <%= f.label :abstract %><br>
        <%= f.text_field :abstract %>
      </div>
      <div class="field">
        <% @technologies.each do |tech| %>
          <input type="checkbox" name="technologies[]" id="<%= tech.name %>" value="<%= tech.id %>"><label for="<%= tech.name %>"><%= tech.name %></label>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :picture %></br>
        <%= f.file_field :picture, as: :file %>
      </div>
    </div>
    <div class="actions">
      <input type="submit" class="btn btn-raised btn-success">
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<main class="container project">
  <div class="row edit">
    <h1>Editing Project</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @project, class: "btn btn-raised btn-info" %> |
    <%= link_to 'Back', projects_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>

app/views/projects/index.html.erb
<main class="container project">
  <div class="row index">
    <p id="notice"><%= notice %></p>

    <h1>Listing Projects</h1>

    <table>
      <thead>
        <tr>
          <th>Image</th>
          <th>Title</th>
          <th>Description</th>
          <th>Github</th>
          <th>Twitter</th>
          <th>Url</th>
          <th>Startdate</th>
          <th>Enddate</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= image_tag project.picture.url(:thumb) %></td>
            <td><%= project.title %></td>
            <td><%= project.description[0..20] %></td>
            <td><a href="<%= project.github %>" target="_blank" ><i class="fa fa-github fa-3x"></i></a></td>
            <td><a href="<%= project.twitter %>" target="_blank" ><i class="fa fa-twitter fa-3x"></i></a></td>
            <td><a href="<%= project.url %>" target="_blank" ><i class="fa fa-link fa-3x"></i></a></td>
            <td><%= project.startdate %></td>
            <td><%= project.enddate %></td>
            <td><%= link_to '', project, :class => "fa fa-eye fa-3x" %></td>
            <td><%= link_to '', edit_project_path(project), :class => "fa fa-pencil fa-3x" %></td>
            <td><%= link_to '', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash fa-3x" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Project', new_project_path, class: "btn btn-raised btn-success" %>
  </div>
</main>

app/views/projects/new.html.erb
<main class="container project">
  <div class="row">
    <h1>New Project</h1>

    <%= render 'form' %>

    <%= link_to 'Back', projects_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>

app/views/projects/show.html.erb
<main class="container project">
  <div class="row show">
    <p id="notice"><%= notice %></p>
    <h1 class="align-center"><%= @project.title %></h1>
    <h3 class="align-center">Views count => <%= @project.views %></h3>
    <div class="col-md-6 col-xs-12">
      <div>
        <%= image_tag @project.picture.url(:medium) %>
      </div>


      <p>
        <strong>Description:</strong>
        <%= @project.description %>
      </p>

      <p>
        <strong>Github:</strong>
        <%= @project.github %>
      </p>

      <p>
        <strong>Twitter:</strong>
        <%= @project.twitter %>
      </p>

      <p>
        <strong>Url:</strong>
        <%= @project.url %>
      </p>
    </div>
    <div class="col-md-6 col-xs-12">
      <p>
      <strong>Startdate:</strong>
        <%= @project.startdate %>
      </p>

      <p>
        <strong>Enddate:</strong>
        <%= @project.enddate %>
      </p>

      <p>
        <strong>Abstract:</strong>
        <%= @project.abstract %>
      </p>
      <h3>Technologies</h3>
      <ul>
       <% @technologies.each do |technology| %>
          <li><%= technology.name %></li>
        <% end %>
      </ul>
    </div>

    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-raised btn-info" %> |
    <%= link_to 'Back', projects_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>