config/routes.rb
Rails.application.routes.draw do
  resources :technologies
  resources :projects
  get 'messages/list'

  resources :depenses
  devise_for :users
  get '/home' => 'pages#home'
  get '/portfolio' => 'pages#portfolio'
  get '/contact' => 'pages#contact'

  get '/project/:id' => 'pages#project'

  get '/pages/paye' => 'pages#paye'

  get '/messages' => 'messages#list'
  delete '/messages/:id' => 'messages#destroy'

  post '/pages/paye' => 'pages#addPaye'
  post 'contact' => 'pages#create'

  root 'pages#home'

end

app/controllers/depenses_controller.rb
class DepensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_depense, only: [:show, :edit, :update, :destroy]

  # GET /depenses
  # GET /depenses.json
  def index
    @depenses = Depense.all
    @total = 0
    @depenses.each do |dep|
      @total += dep.value
    end
    @solde = User.find(1).solde
  end

  # GET /depenses/1
  # GET /depenses/1.json
  def show
  end

  # GET /depenses/new
  def new
    @depense = Depense.new
  end

  # GET /depenses/1/edit
  def edit
  end

  # POST /depenses
  # POST /depenses.json
  def create
    @depense = Depense.new(depense_params)

    respond_to do |format|
      if @depense.save
        format.html { redirect_to @depense, notice: 'Depense was successfully created.' }
        format.json { render :show, status: :created, location: @depense }
        me = User.find(1)
        me.solde = me.solde - @depense.value
        me.save
      else
        format.html { render :new }
        format.json { render json: @depense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depenses/1
  # PATCH/PUT /depenses/1.json
  def update
    respond_to do |format|
      if @depense.update(depense_params)
        format.html { redirect_to @depense, notice: 'Depense was successfully updated.' }
        format.json { render :show, status: :ok, location: @depense }
      else
        format.html { render :edit }
        format.json { render json: @depense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depenses/1
  # DELETE /depenses/1.json
  def destroy
    @depense.destroy
    respond_to do |format|
      format.html { redirect_to depenses_url, notice: 'Depense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_depense
      @depense = Depense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def depense_params
      params.require(:depense).permit(:title, :value, :date, :checked)
    end
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/views/depenses/_form.html.erb
<%= form_for(@depense) do |f| %>
  <% if @depense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@depense.errors.count, "error") %> prohibited this depense from being saved:</h2>

      <ul>
      <% @depense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: "control-label", for: "title" %>
    <%= f.text_field :title, class: "form-control", id: "title" %>
  </div>
  <div class="field form-group">
    <%= f.label :value, class: "control-label", for: "value" %>
    <%= f.text_field :value, class: "form-control", id: "value" %>
  </div>
  <div class="field form-group">
    <%= f.label :date, class: "control-label", for: "date" %>
    <%= f.date_select :date, class: "form-control", id: "date" %>
  </div>
  <div class="field form-group">
    <%= f.label :checked, class: "control-label", for: "checked" %>
    <%= f.number_field :checked, class: "form-control", id: "checked" %>
  </div>
  <div class="actions">
    <%= f.submit "Validate" , class: "btn btn-flat btn-info" %>
  </div>
<% end %>

app/views/depenses/edit.html.erb
<main class="container edit-depense">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Editing Depense</h1>

      <%= render 'form' %>

      <%= link_to @depense, class: "btn btn-flat btn-info" do %>
        <i class="fa fa-eye"></i>&nbsp; Show
      <% end %>
      <%= link_to depenses_path, class: "btn btn-flat btn-warning" do %>
        <i class="fa fa-arrow-left"></i>&nbsp; Back
      <% end %>
    </div>
  </div>
</main>

app/views/depenses/index.html.erb
<main class="container depenses">
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <% if notice %>
        <br />
        <p class="alert alert-success" id="notice"><%= notice %></p>
      <% end %>
      <% if flash[:success] %>
        <br />
        <p class="alert alert-success" id="notice"><%= flash[:success] %></p>
      <% end %>
      <h1>Listing Depenses</h1>
      <div class="row">
        <div class="col-xs-6">
          <%= link_to new_depense_path, class: "btn btn-raised btn-warning" do %>
            <i class="fa fa-plus"></i>&nbsp; New Depense
          <% end %>
        </div>
        <div class="col-xs-6">
          <a href="/pages/paye" class="btn btn-raised btn-info"><i class="fa fa-usd"></i>&nbsp; Add Money</a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Solde</h3>
            </div>
            <div class="panel-body">
              <%= @solde %> €
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title">Total des dépenses</h3>
            </div>
            <div class="panel-body">
              <%= @total %> €
            </div>
          </div>
        </div>
      </div>
      <div class="row title-depense align-center">
        <div class="col-md-2 col-sm-2 col-xs-2">Title</div>
        <div class="col-md-2 col-sm-2 col-xs-2">Value</div>
        <div class="col-md-4 col-sm-4 col-xs-4">Date</div>
        <div class="col-md-2 col-sm-2 col-xs-2">Edit</div>
        <div class="col-md-2 col-sm-2 col-xs-2">Dest</div>
      </div>
      <% @depenses.each do |depense| %>
        <div class="row depense align-center">
          <div class="col-md-2 col-sm-2 col-xs-2"><%= depense.title %></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><%= depense.value %></div>
          <div class="col-md-4 col-sm-4 col-xs-4"><%= depense.date %></div>
          <div class="col-md-2 col-sm-2 col-xs-2">
            <%= link_to edit_depense_path(depense), class: "action-depense" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2">
            <%= link_to depense, method: :delete, data: { confirm: 'Are you sure?' }, class: "destroy action-depense" do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/depenses/new.html.erb
<main class="container new-depense">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>New Depense</h1>

      <%= render 'form' %>

      <%= link_to depenses_path, class: "btn btn-flat btn-warning" do %>
        <i class="fa fa-arrow-left"></i>&nbsp; Back
      <% end %>
    </div>
  </div>
</main>

app/views/depenses/show.html.erb
<main class="container show-depense">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% if notice %>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
      <p>
        <strong>Title:</strong>
        <%= @depense.title %>
      </p>

      <p>
        <strong>Value:</strong>
        <%= @depense.value %>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @depense.date %>
      </p>

      <p>
        <strong>Checked:</strong>
        <%= @depense.checked %>
      </p>
      <%= link_to edit_depense_path(@depense), class: "btn btn-flat btn-info" do %>
        <i class="fa fa-pencil"></i>&nbsp; Edit
      <% end %>
      <%= link_to depenses_path, class: "btn btn-flat btn-warning" do %>
        <i class="fa fa-arrow-left"></i>&nbsp; Back
      <% end %>
    </div>
  </div>
</main>