config/routes.rb
Rails.application.routes.draw do
  resources :technologies
  resources :projects
  get 'messages/list'

  resources :depenses
  devise_for :users
  get '/home' => 'pages#home'
  get '/portfolio' => 'pages#portfolio'
  get '/contact' => 'pages#contact'

  get '/project/:id' => 'pages#project'

  get '/pages/paye' => 'pages#paye'

  get '/messages' => 'messages#list'
  delete '/messages/:id' => 'messages#destroy'

  post '/pages/paye' => 'pages#addPaye'
  post 'contact' => 'pages#create'

  root 'pages#home'

end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name, :description, :link, :doc, :picture)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
  <% if @technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% @technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :doc %><br>
    <%= f.text_field :doc %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <input type="submit" class="btn btn-raised btn-success" />
  </div>
<% end %>

app/views/technologies/edit.html.erb
<main class="container technology">
  <div class="row edit">
    <h1>Editing Technology</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @technology, class: "btn btn-raised btn-info" %> |
    <%= link_to 'Back', technologies_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>

app/views/technologies/index.html.erb
<main class="container technology">
  <div class="row index">
    <p id="notice"><%= notice %></p>

    <h1>Listing Technologies</h1>

    <table>
      <thead>
        <tr>
          <th>Picture</th>
          <th>Name</th>
          <th>Description</th>
          <th>Link</th>
          <th>Doc</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @technologies.each do |technology| %>
          <tr>
            <td><%= image_tag technology.picture.url(:thumb) %></td>
            <td><%= technology.name %></td>
            <td><%= technology.description[0..20] %></td>
            <td><a href="<%= technology.link %>" target="_blank"><i class="fa fa-link fa-3x"></i></a></td>
            <td><a href="<%= technology.doc %>" target="_blank"><i class="fa fa-book fa-3x"></i></a></td>
            <td><%= link_to '', technology, :class => "fa fa-eye fa-3x" %></td>
            <td><%= link_to '', edit_technology_path(technology), :class => "fa fa-pencil fa-3x" %></td>
            <td><%= link_to '', technology, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash fa-3x" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Technology', new_technology_path, class: "btn btn-raised btn-success" %>
  </div>
</main>

app/views/technologies/new.html.erb
<main class="container technology">
  <div class="row new">
    <h1>New Technology</h1>

    <%= render 'form' %>

    <%= link_to 'Back', technologies_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>

app/views/technologies/show.html.erb
<main class="container technology">
  <div class="row show">
    <p id="notice"><%= notice %></p>
    <div><%= image_tag @technology.picture.url(:thumb) %></div>
    <p>
      <strong>Name:</strong>
      <%= @technology.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @technology.description %>
    </p>

    <p>
      <strong>Link:</strong>
      <%= @technology.link %>
    </p>

    <p>
      <strong>Doc:</strong>
      <%= @technology.doc %>
    </p>

    <%= link_to 'Edit', edit_technology_path(@technology), class: "btn btn-raised btn-info" %> |
    <%= link_to 'Back', technologies_path, class: "btn btn-raised btn-danger" %>
  </div>
</main>